// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMtSgsZuHAwh6k_DCLs-9QKaCJuY55_K0',
    appId: '1:861954482863:web:4927db2831ffb572e7aa5a',
    messagingSenderId: '861954482863',
    projectId: 'classycode-d6e56',
    authDomain: 'classycode-d6e56.firebaseapp.com',
    storageBucket: 'classycode-d6e56.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlz-et3Th8gQ4_JRVGGx-lJLwI-k5RVNU',
    appId: '1:861954482863:android:57fe37cec3d4b9fbe7aa5a',
    messagingSenderId: '861954482863',
    projectId: 'classycode-d6e56',
    storageBucket: 'classycode-d6e56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzFT3BFBbdKojCxofP1j25EsXFFfK-Fgg',
    appId: '1:861954482863:ios:bec5325903cf4f40e7aa5a',
    messagingSenderId: '861954482863',
    projectId: 'classycode-d6e56',
    storageBucket: 'classycode-d6e56.appspot.com',
    iosBundleId: 'com.example.classyCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzFT3BFBbdKojCxofP1j25EsXFFfK-Fgg',
    appId: '1:861954482863:ios:bec5325903cf4f40e7aa5a',
    messagingSenderId: '861954482863',
    projectId: 'classycode-d6e56',
    storageBucket: 'classycode-d6e56.appspot.com',
    iosBundleId: 'com.example.classyCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMtSgsZuHAwh6k_DCLs-9QKaCJuY55_K0',
    appId: '1:861954482863:web:b3dbfa1a1c1b576be7aa5a',
    messagingSenderId: '861954482863',
    projectId: 'classycode-d6e56',
    authDomain: 'classycode-d6e56.firebaseapp.com',
    storageBucket: 'classycode-d6e56.appspot.com',
  );

}